import {
  FileText,
  Download,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  Clock,
  BarChart3,
  Activity,
} from "lucide-react";
import { useState } from "react";

interface Report {
  id: string;
  title: string;
  type: string;
  period: string;
  status: "Ready" | "Generating";
  generated: string;
}

const initialReports: Report[] = [
  {
    id: "RPT-2026-008",
    title: "Monthly Security Operations Report",
    type: "Security Operations",
    period: "September 2026",
    status: "Ready",
    generated: "Today, 10:30 AM",
  },
  {
    id: "RPT-2026-007",
    title: "Incident Response Summary",
    type: "Incident Response",
    period: "September 2026",
    status: "Ready",
    generated: "Today, 09:45 AM",
  },
  {
    id: "RPT-2026-006",
    title: "Healthcare System Security Report",
    type: "System Security",
    period: "August 2026",
    status: "Ready",
    generated: "Sep 01, 2026",
  },
  {
    id: "RPT-2026-005",
    title: "Security Alert Analysis",
    type: "Alert Analysis",
    period: "August 2026",
    status: "Ready",
    generated: "Sep 01, 2026",
  },
];

export default function Reports() {
  const [reports, setReports] = useState<Report[]>(initialReports);
  const [message, setMessage] = useState("");

  const generateReport = () => {
    const newReport: Report = {
      id: `RPT-2026-${String(reports.length + 9).padStart(3, "0")}`,
      title: "Security Operations Report",
      type: "Security Operations",
      period: "September 2026",
      status: "Generating",
      generated: "Just now",
    };

    setReports((current) => [newReport, ...current]);
    setMessage("Report generation started.");

    setTimeout(() => {
      setReports((current) =>
        current.map((report) =>
          report.id === newReport.id
            ? { ...report, status: "Ready" }
            : report
        )
      );

      setMessage("Report generated successfully.");
    }, 1500);

    setTimeout(() => {
      setMessage("");
    }, 4000);
  };

  const downloadReport = (report: Report) => {
    const reportContent = `
CYBERMED RESPONSE
Security Report
==============================

Report ID: ${report.id}
Report Title: ${report.title}
Report Type: ${report.type}
Reporting Period: ${report.period}
Generated: ${report.generated}
Status: ${report.status}

SECURITY SUMMARY
------------------------------
System Availability: 99.8%
Security Incidents: 4
Resolution Rate: 87%
Security Events: 128

This report was generated by the CyberMed Response
healthcare cybersecurity platform.

Environment: Demo Environment
    `.trim();

    const blob = new Blob([reportContent], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.id}-CyberMed-Report.txt`;

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);

    setMessage(`${report.id} downloaded successfully.`);

    setTimeout(() => {
      setMessage("");
    }, 3000);
  };

  return (
    <div className="module-page">

      {/* HEADER */}
      <div className="module-header">

        <div>
          <div className="module-label">
            SECURITY OPERATIONS
          </div>

          <h1>Security Reports</h1>

          <p>
            Review security activity, incident response
            and system protection reports.
          </p>
        </div>

        <div className="alert-header-icon">
          <FileText size={22} />
        </div>

      </div>

      {/* SUCCESS / STATUS MESSAGE */}
      {message && (
        <div className="response-success-message">
          <CheckCircle size={20} />

          <div>
            <strong>{message}</strong>

            <span>
              CyberMed Response reporting system updated successfully.
            </span>
          </div>
        </div>
      )}

      {/* SUMMARY */}
      <div className="incident-summary">

        <div className="summary-card">
          <div className="summary-icon critical-icon">
            <AlertTriangle size={20} />
          </div>

          <div>
            <span>Incidents</span>
            <strong>4</strong>
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-icon high-icon">
            <Activity size={20} />
          </div>

          <div>
            <span>Alerts</span>
            <strong>12</strong>
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-icon investigating-icon">
            <Clock size={20} />
          </div>

          <div>
            <span>Under Response</span>
            <strong>2</strong>
          </div>
        </div>

        <div className="summary-card">
          <div className="summary-icon resolved-icon">
            <CheckCircle size={20} />
          </div>

          <div>
            <span>Resolved</span>
            <strong>7</strong>
          </div>
        </div>

      </div>

      {/* SECURITY OVERVIEW */}
      <section className="report-overview">

        <div className="panel-heading">

          <div>
            <h2>Security Overview</h2>

            <p>
              Current security activity across monitored
              healthcare infrastructure.
            </p>
          </div>

        </div>

        <div className="report-metrics">

          <div className="report-metric">
            <div className="report-metric-icon">
              <ShieldCheck size={20} />
            </div>

            <div>
              <span>System Availability</span>
              <strong>99.8%</strong>
            </div>
          </div>

          <div className="report-metric">
            <div className="report-metric-icon">
              <AlertTriangle size={20} />
            </div>

            <div>
              <span>Security Incidents</span>
              <strong>4</strong>
            </div>
          </div>

          <div className="report-metric">
            <div className="report-metric-icon">
              <CheckCircle size={20} />
            </div>

            <div>
              <span>Resolution Rate</span>
              <strong>87%</strong>
            </div>
          </div>

          <div className="report-metric">
            <div className="report-metric-icon">
              <BarChart3 size={20} />
            </div>

            <div>
              <span>Security Events</span>
              <strong>128</strong>
            </div>
          </div>

        </div>

      </section>

      {/* REPORT LIST */}
      <section className="incidents-container">

        <div className="panel-heading">

          <div>
            <h2>Available Reports</h2>

            <p>
              Security reports generated by the platform.
            </p>
          </div>

          <button
            className="view-all-button"
            type="button"
            onClick={generateReport}
          >
            Generate Report
          </button>

        </div>

        <div className="reports-list">

          {reports.map((report) => (

            <div
              className="report-card"
              key={report.id}
            >

              {/* REPORT ICON */}
              <div className="report-icon">
                <FileText size={21} />
              </div>

              {/* REPORT DETAILS */}
              <div className="report-details">

                <div className="report-id">
                  {report.id}
                </div>

                <h3>
                  {report.title}
                </h3>

                <div className="report-meta">

                  <span>
                    {report.type}
                  </span>

                  <span>
                    {report.period}
                  </span>

                  <span>
                    {report.generated}
                  </span>

                </div>

              </div>

              {/* STATUS */}
              <span
                className={`status-badge ${
                  report.status === "Ready"
                    ? "resolved"
                    : "investigating"
                }`}
              >
                {report.status}
              </span>

              {/* DOWNLOAD */}
              <button
                className="report-download"
                type="button"
                title={
                  report.status === "Ready"
                    ? "Download report"
                    : "Report is still generating"
                }
                disabled={report.status !== "Ready"}
                onClick={() => downloadReport(report)}
              >
                <Download size={17} />
              </button>

            </div>

          ))}

        </div>

      </section>

      {/* REPORT NOTICE */}
      <div className="response-notice">

        <ShieldCheck size={18} />

        <div>

          <strong>
            Secure Reporting
          </strong>

          <span>
            Reports provide a consolidated view of
            security events, incidents and response
            activities for authorized users.
          </span>

        </div>

      </div>

    </div>
  );
}